### PR TITLE
PLT-3366 Holding down the ALT key and clicking on a message adds a new messages indicator

### PR DESCRIPTION
**Pull request by samogot**
https://mattermost.atlassian.net/browse/PLT-3366
Correspondent PR: https://github.com/mattermost/platform/pull/3374

### CODE REVIEW

**Comment by enahum** [comment]
@samogot if I remember correctly there is a function called `updateLastViewedAt` can you please verify and if thats the case please use that one and close this PR.

Thanks.

**Comment by samogot** [comment]
@enahum No, `updateLastViewedAt` is a different function that updates last viewed position to last post. this function allows to set any lastViewedAt timestamp

**Comment by enahum** [comment]
+1

**Comment by jwilander** [comment]
+1

**Pull request merged**
