### PR TITLE
PLT-1800 Set client Accept-Language in default headers

### PR DESCRIPTION
**Pull request by enahum**
This add the ability to set `Accept-Language Header` for every request. Needed for getting localize messages from the server

### CODE REVIEW

**Comment by enahum** [comment]
This should be merged and publish in order to fix the problem we're havig in pre-release

**Comment by hmhealey** [comment]
+1 Not sure of our review process here though

**Comment by jwilander** [comment]
+1

**Comment by crspeller** [comment]
Why are we overriding Accept-Language?

**Comment by enahum** [comment]
Cause we need that in order to get the translated messages from the server in the same language as the user's UI

**Pull request merged**
