### PR TITLE
PLT-2863 adding remove from team to javascript driver

### PR DESCRIPTION
**Pull request by coreyhulen**

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by enahum** [comment]
+1

**Comment by enahum** [comment]
@coreyhulen should we hold this until https://github.com/mattermost/platform/pull/3429 is in?

**Comment by coreyhulen** [comment]
yup...lets hold it off.  I'll merge it when ready.

**Comment by enahum** [comment]
+1 if no more work is needed and test have to be commented

**Pull request merged**
