### PR TITLE
PLT-3144 Added APIs to list, add, and delete custom emojis

### PR DESCRIPTION
**Pull request by hmhealey**
Don't merge until after we've tagged/branched for 3.1

### CODE REVIEW

**Comment by jwilander** [comment]
+1

**Comment by enahum** [comment]
+1

**Comment by hmhealey** [comment]
Marking this as DO NOT MERGE since I keep having to make changes to the method signatures

**Comment by hmhealey** [comment]
K the APIs are finalized and should be ready to go in

**Comment by enahum** [comment]
+1 with the new changes

**Pull request merged**
